version: '3.1'

services:
  db-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - ./dumps/bankaccount/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password

  mq-rabbitmq:
    image: rabbitmq:3.8-alpine
    restart: always
    hostname: mq-rabbitmq
    # todo: do not expose port 5672 to host.
    ports:
    - 5672:5672

  be-bankaccount:
    depends_on:
      - db-mysql
      - mq-rabbitmq
    image: be-bankaccount
    ports:
    - 8443:8443
    restart: always
    env_file:
      - be-bankaccount.env
    environment:
      spring.datasource.url: jdbc:mysql://db-mysql:3306/bankaccount
      spring.rabbitmq.host: mq-rabbitmq