# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
          ssh -o StrictHostKeyChecking=no root@${{ secrets.HOSTNAME }} "rm -rf be-bankaccount; \
            git clone https://github.com/kidfrom/be-bankaccount.git; cd be-bankaccount; \
            echo $'\n'spring.profiles.active=development >> src/main/resources/application.properties; \
            echo ${{ secrets.be_bankaccount }} > be-bankaccount.env; \
            yes | cp ${{ secrets.KEYSTOREPATH }}/keystore.p12 src/main/resources/keystore.p12; \
            docker build -t be-bankaccount .; \
            docker rmi $(docker images -f "dangling=true" -q); \
            docker-compose up -d;"
